/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package org.chromium.content;

public final class R {
	public static final class id {
		public static final int month = 0x7f09002d;
		public static final int year = 0x7f09002e;
		public static final int time_picker = 0x7f090029;
		public static final int date_picker = 0x7f090028;
		public static final int pickers = 0x7f09002c;
	}
	public static final class string {
		public static final int actionbar_share = 0x7f050002;
		public static final int accessibility_datetime_picker_time = 0x7f05000b;
		public static final int actionbar_web_search = 0x7f050003;
		public static final int date_picker_dialog_title = 0x7f050007;
		public static final int date_time_picker_dialog_title = 0x7f050008;
		public static final int media_player_error_text_invalid_progressive_playback = 0x7f05000f;
		public static final int date_picker_dialog_clear = 0x7f050006;
		public static final int accessibility_date_picker_month = 0x7f05000c;
		public static final int media_player_error_text_unknown = 0x7f050010;
		public static final int accessibility_date_picker_year = 0x7f05000d;
		public static final int media_player_error_title = 0x7f05000e;
		public static final int media_player_loading_video = 0x7f050012;
		public static final int accessibility_datetime_picker_date = 0x7f05000a;
		public static final int media_player_error_button = 0x7f050011;
		public static final int accessibility_content_view = 0x7f050004;
		public static final int date_picker_dialog_set = 0x7f050005;
		public static final int month_picker_dialog_title = 0x7f050009;
	}
	public static final class layout {
		public static final int date_time_picker_dialog = 0x7f040007;
		public static final int month_picker = 0x7f040009;
	}
	public static final class drawable {
		public static final int ic_menu_share_holo_light = 0x7f020003;
		public static final int ondemand_overlay = 0x7f020005;
		public static final int ic_menu_search_holo_light = 0x7f020002;
	}
	public static final class dimen {
		public static final int link_preview_overlay_radius = 0x7f060000;
	}
	public static final class array {
		public static final int official_command_line = 0x7f070000;
	}
}
